Repository emmeowzing/dynamic-continuation-orb, pull requests merged in 2023-03, with the labels that each got.

#29 Add pre-script support
  src/jobs/continue.yml
Labels: feature

#31 Fix the update check
  package.json
Labels: bug

#33 Extract scripts
  .circleci/src.yml
  .pre-commit-config.yaml
  scripts/validate.sh
  src/commands/filter.yml
  src/commands/reduce.yml
  src/examples/dynamic_continuation_pipeline.yml
  src/jobs/continue.yml
  src/scripts/.placeholder
  src/scripts/filter.sh
  src/scripts/reduce.sh
Labels: feature

#32 repo-updates: Update repo settings
  .circleci/config.yml
  .circleci/src.yml
  .github/PULL_REQUEST_TEMPLATE/PULL_REQUEST.md
  .github/settings.yml
  .github/stale.yml
  .pre-commit-config.yaml
  .tool-versions
  package.json
  scripts/validate.sh
  src/commands/filter.yml
  src/commands/reduce.yml
  src/examples/dynamic_continuation_pipeline.yml
  src/jobs/continue.yml
  src/scripts/.placeholder
  src/scripts/filter.sh
  src/scripts/reduce.sh
Labels: config updates

#27 ENG-138: Fix filtered modules
  .circleci/config.yml
  .pre-commit-config.yaml
  src/commands/filter.yml
  src/commands/reduce.yml
  src/executors/python.yml
  src/jobs/continue.yml
  src/scripts/filter.sh
  src/scripts/reduce.sh
Labels: bug

#34 remove-modules-dependency: Remove unnecessary modules listing
  .circleci/config.yml
  .github/ISSUE_TEMPLATE/BUG.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/auto_assign.yml
  README.md
  src/commands/filter.yml
  src/commands/reduce.yml
  src/jobs/continue.yml
  src/scripts/filter.sh
  src/scripts/reduce.sh
Labels: feature

#36 fix-config-changes: Debug env var
  src/scripts/filter.sh
Labels: bug

#38 fix-auto-detection: root-config not adequately handled
  .tool-versions
  scripts/dependencies.sh
  src/@orb.yml
  src/commands/filter.yml
  src/scripts/filter.sh
Labels: bug

#40 require-approval: Add slack approval
  .circleci/config.yml
Labels: Improvement

#45 merge-pre-commit-hooks: Merge projects
  .pre-commit-hooks.yaml
  README.md
  scripts/circleci-config-validate.sh
Labels: Config updates
